# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db13b19aafe35922c64bbd6b77780f93425a8af48d431aeec50662e14e9919d0d6d26e8c5136ad9cabbac0bc0d83558f5829c91a515eb90028f2d3254a1a4603

test:
  secret_key_base: 007391eb0f759876b58216378a6afb846225eea9af9fcf068e0b98625c0e2cc0ce640a8019559fa909cab4ec39dbb22c08bcad09d7cb04012aaa4d4ab6c35ba4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
